name: "refresh"

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认 token

      - name: Install Dependencies
        run: |
          sudo apt update -qq
          sudo apt install dpkg-dev bzip2 xz-utils zstd -y

      - name: Refresh Packages
        run: |
          rm -rf ./Packages*
          dpkg-scanpackages -m ./debs /dev/null >./Packages
          bzip2 -v -k -9 Packages
          xz -v -k -9 --extreme Packages
          zstd --ultra -22 -k Packages -o Packages.zst

      - name: Configure Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > $HOME/.git-credentials

      - name: Commit Changes
        run: |
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Refresh Packages by ${{ github.actor }}"
          fi

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull --rebase  # 确保是最新版本
          git push origin main

      # 以下步骤保留但优化了环境变量
      - name: Download remove_all_actions
        run: |
          sudo curl -L -o '/usr/bin/remove_all_actions' 'https://raw.githubusercontent.com/invalidunit/action/main/remove_all_actions'
          sudo chmod -R 0755 '/usr/bin/remove_all_actions'

      - name: Remove All Old Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          remove_all_actions
